### ISSUE TITLE
NSRegularExpression and OSX 10.6

### ISSUE THREAD

**Issue by u10int** [tomaz/appledoc#171]
Just tried updating to the latest 2.x release and received several compiler errors in GBTokenizer.m about NSRegularExpression. I'm running OSX 10.6 and the latest stable version of Xcode (4.2), but NSRegularExpression is only available in the Foundation.framework on OSX 10.7. However, the requirements for appledoc don't state OSX 10.7 is required for compiling.

appledoc/Parsing/GBTokenizer.m:320:2: error: use of undeclared identifier 'NSRegularExpression' [3]
         NSRegularExpression _directiveExpression = [NSRegularExpression regularExpressionWithPattern:@"^\s_@(param|result|return)" options:NSRegularExpressionDotMatchesLineSeparators error:nil];

Is there an alternative solution for compiling on OSX 10.6? I notice versions prior to 2.0 were using RegexLiteKit instead...
